-
  text: Butter Pecan
  img: http://www.bakeorbreak.com/wp-content/uploads/2016/05/butter_pecan_cheesecake0883_1k.jpg
-
  text: Vanilla Ice Cream
  img: https://addapinch.com/wp-content/blogs.dir/3/files/2014/07/old-fashioned-vanilla-ice-cream-recipe-DSC_4239.jpg
-
  text: Cotton Candy
  img: https://www.cookingclassy.com/wp-content/uploads/2015/07/cotton-candy-cupcakes5-srgb.jpg   
-
  text: Butter Pecan
  img: http://www.bakeorbreak.com/wp-content/uploads/2016/05/butter_pecan_cheesecake0883_1k.jpg
-
  text: Vanilla Ice Cream
  img: https://addapinch.com/wp-content/blogs.dir/3/files/2014/07/old-fashioned-vanilla-ice-cream-recipe-DSC_4239.jpg
-
  text: Cotton Candy
  img: https://www.cookingclassy.com/wp-content/uploads/2015/07/cotton-candy-cupcakes5-srgb.jpg      
-
  text: Butter Pecan
  img: http://www.bakeorbreak.com/wp-content/uploads/2016/05/butter_pecan_cheesecake0883_1k.jpg
-
  text: Vanilla Ice Cream
  img: https://addapinch.com/wp-content/blogs.dir/3/files/2014/07/old-fashioned-vanilla-ice-cream-recipe-DSC_4239.jpg
-
  text: Cotton Candy
  img: https://www.cookingclassy.com/wp-content/uploads/2015/07/cotton-candy-cupcakes5-srgb.jpg
-
  text: Strawberry Kiwi
  img: http://sportsvape.net/wp-content/uploads/2014/09/Strawberry-Kiwi.jpg               